spring:
  profiles: local
  datasource:
      url: jdbc:mysql://124.221.52.209:3306/ulm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: Zlzx!1988
      #url: jdbc:mysql://localhost:5106/ulm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      #username: 123456
      #password: 123456
logging:
  config: classpath:logback-local.xml
